default: &default
  adapter: postgresql
  encoding: unicode
  username: myapp_user
  password: secure_password
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_db

test:
  <<: *default
  database: myapp_db_test

production:
  <<: *default
  database: myapp_db_production
  username: myapp_user
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
